language: python
python:
- '2.7'
- '2.6'
install:
- git config --global user.name  "Travis CI"
- git config --global user.email "pdc@product-definition-center.com"
- export REPO_URL_GITHUB="https://$GH_TOKEN@github.com/$GH_REPO.git"
- if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install importlib unittest2; fi
- pip install -U pip wheel coveralls
- pip install -r requirements/devel.txt
script:
- flake8 . --config=tox.ini
- coverage run --source=pdc_client client_test_run.py
- if [ "$TRAVIS_PYTHON_VERSION" = "2.7" -a "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then make -C docs/ setup_gh_pages gen_deploy; fi
after_success:
- coveralls
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
env:
  global:
  - GH_REPO="product-definition-center/pdc-client"
  - secure: bhxSTEJjXiOiUaOdJsyEQLjHfdwOVwPRgcC5Qp2eNPEv+Y4VJiszDJ8wQqRuAQa31HMujbwjxI1llP7rkpsxZp6jHs71MDy20TmnBJThV7CW/U0yHhlmyXg/2TyUeFIGs7kzlCWqTaZpDQZ85EyvIYyrys2tBLguRWn6mRJo4s55MUemupxRYM1DLVM4bVVzHvr/j33XQQxK9QBDasgb7T5YC4uxjQ1o5Ni4EQ2AxHqHYJQW1wDMzIiqCKfBRJJQVp7ewyu1oKbSD1gCYtZwf9BAhBW0XLchghzY+moMysHSIp6DXE0g4BIayInuxFRTlzOa6/1tVUOT7xoz8CEPzqwIjszkAHmMuhegkCFKeMW9v64xhR4lsDec/EzL4iL/kryJmB1wDT3r9nVXWmYAd5S8L4YjLVOIqfMAQt7E3ehMoFsd6ckK9qbguDi4ACkENY3U9GLPIEcaNTXh0PzcL+AWk6qtRj1QKGtaVlCAdgcJ+ZsJT+jyzfO3sU8/P9beqbO8o+572zTfxXeJBAus2UAwaNd24VwNcQuAFjy5TlUNEBmSI541JRG1cK0uMioycekW5t99Pt/q8ijfPpSU0tI/zGk+HTj8l0SoLsBdo/cHAEoRhGiJFl/kP8Qhq72cq1tq4OFAZ/kUZ2/FiJQhAjhkFFk+tacnXRVeXtWK28w=
