language: python
python:
    - "2.7"
    - "2.6"
install:
    - git config --global user.name  "Travis CI"
    - git config --global user.email "pdc@product-definition-center.com"
    - export REPO_URL_GITHUB="https://$GH_TOKEN@github.com/$GH_REPO.git"
    - pip install -U pip wheel coveralls
    - pip install -r requirements/devel.txt
script:
    - flake8 . --config=tox.ini
    - coverage run --source=pdc_client client_test_run.py
after_success:
    - coveralls
cache:
    directories:
        - $HOME/.cache/pip
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
env:
    global:
    - GH_REPO="product-definition-center/pdc-client"
    - secure: "IM5TrZgax/l70/4RdvVRYf9xgexBdX+EJFvjlDZKeIMJqaDp8j6pC3UXWw/L1GGWNr5JZPesFC//HsJpJ5AOmAGiviDontOyXNlQfBdj6KhNbKNEuzBI1XBAtHhuK3n5Jt7LwTEWgnS/1gmFxS/quWrjzCZEIfpERi1bi1/mDa6UeChQNyILsld7ehLo32+3PFixNAFpzrmY8UmM2oCmxVYQLspRQsXO82Vrzz+4apBzxXR6VXCqXX6x73b4dLRcktwgo7RYycIPFd4SS/tPlVy+On3RPUWHCu/vM9oGr49i33hfA3dYxU5tqymUsDtCS5Fz0bTFwlqBHH4ivZNuhr5j4BvWXkHaqBVEOeuVl9ljabQqPytupVLpooG3PHMNcFFqqOs30j4wQIFgNr7diH0i0uAoGiFMf7vThNr5QC3zG+0nIkqtFzBLFGY8lMy0CYxABeCAmt9GJU3ikzpRx7sNdDnDdNX0TqlSwYTWlUtWFKFuHUmNLvhhRHO4KwebG+SRbAcaEB2886+PwnbnZb8gADWmnWcScQ4qt18SWuq5hb+aJ0lP80LRBL7vqP1y2DWBuTgb84ZDemqKCnTuSWHuBc7W9wFAP4nEZvkOSJdJYqOBu44LShtUPbcmbJ6LEdgVtS+6HxbNSEVjAWlwaZ7vWKGpnMfyoCcn5miXkjo="
